spring:
  application:
    name: employee-api

server:
  port: 8080

mock-api:
  base-url: http://localhost:8112/api/v1/employee
  connection-timeout: 5000
  read-timeout: 10000
  retry:
    max-attempts: 25
    initial-delay: 1000
    max-delay: 5000
    multiplier: 2.0

logging:
  level:
    com.reliaquest.api: DEBUG
    org.springframework.web.reactive.function.client: DEBUG